#!/bin/bash
set -euxo pipefail

# Run prisma init
cd /app/example-app/backend
npx prisma init

# Create schema file
cat <<-EOF > /app/example-app/backend/prisma/schema.prisma
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/client"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
EOF
