#!/bin/bash
set -euxo pipefail

echo "Running track setup script on host docker-vm"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Clone training repository
git clone https://github.com/prisma/prisma-fundamentals.git /app

# Remove git repo to prevent VS Code from showing prior versions
rm -rf /app/.git

# Add Prisma and Terminals VS Code Extensions
code-server --install-extension prisma.prisma --user-data-dir /user-data
code-server --install-extension fabiospampinato.vscode-terminals --user-data-dir /user-data

# Disable Trusted workspaces
cat <<-EOF > /user-data/User/settings.json
{
    "security.workspace.trust.startupPrompt": "never",
    "security.workspace.trust.enabled": false,
    "security.workspace.trust.banner": "never",
    "security.workspace.trust.emptyWindow": false
}
EOF

# Install Node.js
# https://github.com/nodesource/distributions/blob/master/README.md
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs

# Remove schema file so students can recreate
rm -rf /app/example-app/backend/prisma/

# NPM Install
cd /app/example-app/backend
npm install