#!/bin/bash
set -euxo pipefail

echo "Running track setup script on host docker-vm"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Make app directory
mkdir /app

# Setup terminal
mkdir /app/.vscode
cat <<-EOF > /app/.vscode/terminals.json
{
    "autorun": true,
    "autokill": true,
    "terminals": [
        {
            "name": "TERMINAL",
            "description": "For running commands",
            "open": true,
            "focus": false,
            "commands": [
                "cd /app/"
            ]
        }
    ]
}
EOF

# Add Prisma and Terminals VS Code Extensions
code-server --install-extension prisma.prisma --user-data-dir /user-data
code-server --install-extension fabiospampinato.vscode-terminals --user-data-dir /user-data

# Disable Trusted workspaces
cat <<-EOF > /user-data/User/settings.json
{
    "security.workspace.trust.startupPrompt": "never",
    "security.workspace.trust.enabled": false,
    "security.workspace.trust.banner": "never",
    "security.workspace.trust.emptyWindow": false
}
EOF

# Install Node.js
# https://github.com/nodesource/distributions/blob/master/README.md
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs

# Install jq
apt-get install -y jq

# NPM Install
cd /app/
npm init -y
npm install prisma