#!/bin/bash
set -euxo pipefail

# Run prisma init
cd /app/backend
npx prisma init
sleep 1

# Create schema file
cat <<-EOF > /app/backend/prisma/schema.prisma
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/client"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_CONNECTION")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
EOF
