#!/bin/bash
set -euxo pipefail

# Check that Prisma can read schema file
cd /app/backend/
ls prisma/schema.prisma || fail-message "schema.prisma file not found"
npx prisma format || fail-message "schema.prisma file cannot be parsed"

# Setup scripts to parse DMMF
cat <<-EOF > /tmp/returnDMMF.js
import pkg from '@prisma/sdk';
const { getDMMF, getSchema, getSchemaPath } = pkg;

const schemaPath = (await getSchemaPath())
const datamodel = await getSchema(schemaPath)
const dmmf = await getDMMF({datamodel: datamodel})

console.log(JSON.stringify(dmmf))
EOF
cat <<-EOF > /tmp/package.json
{
  "type": "module",
  "dependencies": {
    "@prisma/sdk": "^3.14.0"
  }
}
EOF
cd /tmp
npm install
cd /app/backend
node /tmp/returnDMMF.js > /tmp/DMMF.json

# Check Post model
DATABASE_CONNECTION="mysql://mysql"
cat /tmp/DMMF.json | jq '.datamodel.models[] | select(.name=="Post")'.name | grep "Post" || fail-message "Post model not found"
cat /tmp/DMMF.json | jq '.datamodel.models[] | select(.name=="Post").fields[] | select(.name=="id")'.type | grep "Int" || fail-message "id Type is incorrect"
