#!/bin/bash
set -euxo pipefail

# Improperly format schema file
cat <<-EOF > /app/prisma/schema.prisma
generator client {
provider = "prisma-client-js"
output   = "../src/generated/client"
}

datasource db {
provider = "mysql"
url      = env("DATABASE_CONNECTION")
}

model User {
id    Int     @id @default(autoincrement())
email String  @unique
name  String?
posts Post[]
}

model Post {
id        Int      @id @default(autoincrement())
createdAt DateTime @default(now())
updatedAt DateTime @updatedAt
title     String
content   String?
published Boolean  @default(false)
viewCount Int      @default(0)
author    User     @relation(fields: [authorId], references: [id])
authorId  Int
}

enum Role {
VIEWER
EDITOR
ADMIN
}
EOF
